import Link from "next/link";
import { getPublicSiteSettings } from "@/lib/settings";
import { getLocale } from "@/lib/i18n/server";
import { pathForLocale } from "@/lib/i18n/config";

export async function Footer(){
  const [settings,locale]=await Promise.all([getPublicSiteSettings(),getLocale()]);
  const es=locale==="es";
  const href=(path:string)=>pathForLocale(path,locale);
  return <footer className="bg-[#171914] text-[#f4f0e7]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 md:grid-cols-[1.4fr_1fr_1fr] md:px-8"><div><div className="font-display text-3xl font-black tracking-[-.06em]">TENTTOP.</div><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">{es?"Tiendas de techo para escapadas, fines de semana y viajes por carretera, con especificaciones claras y ayuda de compatibilidad desde Barcelona.":"Roof tents for road trips, weekends and overland escapes, with clear specs and fitment support from Barcelona."}</p>{(settings.contactEmail||settings.businessPhone)&&<div className="mt-5 grid gap-1 text-sm text-white/70">{settings.contactEmail&&<a href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a>}{settings.businessPhone&&<a href={`tel:${settings.businessPhone}`}>{settings.businessPhone}</a>}</div>}{Object.values(settings.socialLinks).some(Boolean)&&<div className="mt-5 flex flex-wrap gap-3 text-xs font-bold text-white/65">{Object.entries(settings.socialLinks).filter(([,u])=>u).map(([n,u])=><a key={n} href={u} target="_blank" rel="noreferrer" className="capitalize">{n}</a>)}</div>}</div><div><p className="eyebrow text-white/45">{es?"Explorar":"Explore"}</p><div className="mt-4 grid gap-2 text-sm"><Link href={href("/roof-tents")}>{es?"Tiendas de techo":"Roof tents"}</Link><Link href={href("/compare")}>{es?"Comparar":"Compare"}</Link><Link href={href("/vehicle-compatibility")}>{es?"Compatibilidad del vehículo":"Vehicle compatibility"}</Link><Link href={href("/installation")}>{es?"Instalación":"Installation"}</Link><Link href={href("/delivery")}>{es?"Recogida y entrega":"Collection & delivery"}</Link></div></div><div><p className="eyebrow text-white/45">{es?"Empresa":"Company"}</p><div className="mt-4 grid gap-2 text-sm"><Link href={href("/about")}>{es?"Sobre nosotros":"About"}</Link><Link href={href("/faq")}>{es?"Preguntas frecuentes":"FAQ"}</Link><Link href={href("/contact")}>{es?"Contacto":"Contact"}</Link><Link href={href("/legal/privacy")}>{es?"Privacidad":"Privacy"}</Link><Link href={href("/legal/terms")}>{es?"Términos":"Terms"}</Link></div></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-white/45">© {new Date().getFullYear()} Tenttop · {settings.businessLocation}</div></footer>
}
